### ISSUE TITLE
CSS minify problem with calc()

### ISSUE THREAD

**Issue by TriForceX** [TriForceX/WebsiteBase#14]
Theres a problem with the PHP minify code for CSS when tries to minify calc(). The code is is only keep the spaces in * and / symbols but not in + and - so it will not work.

This code:
```css
.my-style {
   background-position: calc(100% - 50px) calc(100% / 2);
   height: calc(20.5rem + 100%);
}
```
Will result in :
```css
.my-style {
   background-position: calc(100%-50px) calc(100% / 2);
   height: calc(20.5rem+100%);
}
```

The operator symbols without spaces between them will not work.
